study_prefix = "data_metrics"

[table_builder_config]
file_names = [
    "meta/meta.py",
    "c_pt_count/c_pt_count.py",
    "c_pt_deceased_count/c_pt_deceased_count.py",
    "c_resource_count/c_resource_count.py",
    "c_resources_per_pt/c_resources_per_pt.py",
    "c_system_use/c_system_use.py",
    "c_us_core_v4_count/c_us_core_v4_count.py",
    "q_date_recent/q_date_recent.py",
    "q_ref_target_pop/q_ref_target_pop.py",
    "q_ref_target_valid/q_ref_target_valid.py",
    "q_system_use/q_system_use.py",
    "q_valid_us_core_v4/q_valid_us_core_v4.py",
]

[export_config]
export_list = [
    "data_metrics__count_c_pt_count",
    "data_metrics__count_c_pt_deceased_count",
    "data_metrics__count_c_resource_count_allergyintolerance_month",
    "data_metrics__count_c_resource_count_allergyintolerance_year",
    "data_metrics__count_c_resource_count_condition_month",
    "data_metrics__count_c_resource_count_condition_year",
    "data_metrics__count_c_resource_count_device_all",
    "data_metrics__count_c_resource_count_diagnosticreport_month",
    "data_metrics__count_c_resource_count_diagnosticreport_year",
    "data_metrics__count_c_resource_count_documentreference_month",
    "data_metrics__count_c_resource_count_documentreference_year",
    "data_metrics__count_c_resource_count_encounter_month",
    "data_metrics__count_c_resource_count_encounter_year",
    "data_metrics__count_c_resource_count_immunization_month",
    "data_metrics__count_c_resource_count_immunization_year",
    "data_metrics__count_c_resource_count_medication_all",
    "data_metrics__count_c_resource_count_medicationrequest_month",
    "data_metrics__count_c_resource_count_medicationrequest_year",
    "data_metrics__count_c_resource_count_observation_month",
    "data_metrics__count_c_resource_count_observation_year",
    "data_metrics__count_c_resource_count_patient_all",
    "data_metrics__count_c_resource_count_procedure_month",
    "data_metrics__count_c_resource_count_procedure_year",
    "data_metrics__c_resources_per_pt_summary",
    "data_metrics__count_c_system_use_allergyintolerance_code",
    "data_metrics__count_c_system_use_condition_code",
    "data_metrics__count_c_system_use_device_type",
    "data_metrics__count_c_system_use_diagnosticreport_code",
    "data_metrics__count_c_system_use_documentreference_type",
    "data_metrics__count_c_system_use_encounter_class",
    "data_metrics__count_c_system_use_encounter_type",
    "data_metrics__count_c_system_use_immunization_vaccinecode",
    "data_metrics__count_c_system_use_medication_code",
    "data_metrics__count_c_system_use_medicationrequest_medicationcodeableconcept",
    "data_metrics__count_c_system_use_observation_code",
    "data_metrics__count_c_system_use_observation_valuecodeableconcept",
    "data_metrics__count_c_system_use_procedure_code",
    "data_metrics__count_c_us_core_v4_count_allergyintolerance_mandatory",
    "data_metrics__count_c_us_core_v4_count_allergyintolerance_must_support",
    "data_metrics__count_c_us_core_v4_count_condition_mandatory",
    "data_metrics__count_c_us_core_v4_count_condition_must_support",
    "data_metrics__count_c_us_core_v4_count_diagnosticreport_lab_mandatory",
    "data_metrics__count_c_us_core_v4_count_diagnosticreport_lab_must_support",
    "data_metrics__count_c_us_core_v4_count_diagnosticreport_note_mandatory",
    "data_metrics__count_c_us_core_v4_count_diagnosticreport_note_must_support",
    "data_metrics__count_c_us_core_v4_count_documentreference_mandatory",
    "data_metrics__count_c_us_core_v4_count_documentreference_must_support",
    "data_metrics__count_c_us_core_v4_count_encounter_mandatory",
    "data_metrics__count_c_us_core_v4_count_encounter_must_support",
    "data_metrics__count_c_us_core_v4_count_immunization_mandatory",
    "data_metrics__count_c_us_core_v4_count_immunization_must_support",
    "data_metrics__count_c_us_core_v4_count_medication_mandatory",
    "data_metrics__count_c_us_core_v4_count_medication_must_support",
    "data_metrics__count_c_us_core_v4_count_medicationrequest_mandatory",
    "data_metrics__count_c_us_core_v4_count_medicationrequest_must_support",
    "data_metrics__count_c_us_core_v4_count_observation_laboratory_mandatory1",
    "data_metrics__count_c_us_core_v4_count_observation_laboratory_mandatory2",
    "data_metrics__count_c_us_core_v4_count_observation_laboratory_must_support",
    "data_metrics__count_c_us_core_v4_count_observation_smoking_status_mandatory1",
    "data_metrics__count_c_us_core_v4_count_observation_smoking_status_mandatory2",
    "data_metrics__count_c_us_core_v4_count_observation_smoking_status_must_support",
    "data_metrics__count_c_us_core_v4_count_observation_vital_signs_mandatory1",
    "data_metrics__count_c_us_core_v4_count_observation_vital_signs_mandatory2",
    "data_metrics__count_c_us_core_v4_count_observation_vital_signs_mandatory3",
    "data_metrics__count_c_us_core_v4_count_observation_vital_signs_must_support",
    "data_metrics__count_c_us_core_v4_count_patient_mandatory",
    "data_metrics__count_c_us_core_v4_count_patient_must_support",
    "data_metrics__count_c_us_core_v4_count_procedure_mandatory",
    "data_metrics__count_c_us_core_v4_count_procedure_must_support",
    "data_metrics__q_date_recent_summary",
    "data_metrics__q_ref_target_pop_summary",
    "data_metrics__q_ref_target_valid_summary",
    "data_metrics__q_system_use_summary",
    "data_metrics__q_valid_us_core_v4_summary",
    "data_metrics__meta_date",
    "data_metrics__meta_version",
]
